# Add the Java arg to connect this Client Master to Operations Centre
- name: Add Java Args to config file
  lineinfile:
    path: "/etc/default/cloudbees-core-cm"
    line: 'JAVA_ARGS="-Djava.awt.headless=true -DMASTER_ENDPOINT=http://{{ ansible_host }}:{{ http_port }} -DMASTER_OPERATIONSCENTER_ENDPOINT=http://{{ hostvars["cjoc"].ansible_host }}:{{ hostvars["cjoc"].http_port }} -DMASTER_INDEX=1 -DMASTER_NAME={{ inventory_hostname }} -DMASTER_GRANT_ID=fjs2ktwfgd  -DMASTER_WEBSOCKET=true"'
    regexp: '^JAVA_ARGS="(.*)"$'
    backrefs: yes
  become: yes

# Add the Jenkins arg to skip the setup wizard
- name: Add Jenkins Args to config file
  lineinfile:
    path: "/etc/default/cloudbees-core-cm"
    line: 'JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT -Djenkins.install.runSetupWizard=false"'
    regexp: '^JENKINS_ARGS="(.*)"$'
    backrefs: yes
  become: yes

# Install Jenkins plugins
- name: Install plugins
  get_url:
    url: https://jenkins-updates.cloudbees.com/download/plugins/{{ item.name }}/{{ item.version }}/{{ item.name }}.hpi
    dest: "{{ install_dir }}/plugins/{{ item.name }}.jpi"
    force: yes
  become: yes
  with_items:
    - "{{ plugins }}"

# Create the init.groovy.d directory
- name: Create init.groovy.d directory
  file:
    path: "{{ install_dir }}/init.groovy.d"
    state: directory
    owner: cloudbees-core-cm
    group: cloudbees-core-cm
  become: yes

# Copy all the groovy templates over
- name: Copy all groovy templates over
  template:
    src: '{{ item.src }}'
    dest: '{{ install_dir }}/init.groovy.d/{{ item.path }}'
    owner: cloudbees-core-cm
    group: cloudbees-core-cm
  with_filetree: '../templates'
  when: item.state == 'file'
  become: yes

# Move the log file from the previous startup to the side so we can watch new log events
- name: Move log file
  command: 'mv {{ log_dir }}/cloudbees-core-cm.log {{ log_dir }}/cloudbees-core-cm-upto-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}.log'
  become: yes

# Now the setup is done, restart the OC service so changes take affect
- name: Restart the CM service
  service: name=cloudbees-core-cm state=restarted
  become: yes

# Wait for CM to start
- name: Wait for CM to start
  wait_for:
    path: "{{ log_dir }}/cloudbees-core-cm.log"
    search_regex: "Jenkins is fully up and running"
    delay: 10
    timeout: 120
    msg: "Client Master did not start or did not start in a timely manner"

# Make sure that all the groovy startup scripts we copied in have run
- name: Make sure the last groovy startup script ran
  wait_for:
    path: "{{ log_dir }}/cloudbees-core-cm.log"
    search_regex: "j.util.groovy.GroovyHookScript#execute: Executing {{ install_dir }}/init.groovy.d/03-set-jenkins-url.groovy"
    delay: 10
    timeout: 120
    msg: "03-set-jenkins-url.groovy script did not run or did not run in a timely manner"
